# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sprache

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Ensure correct startup script
        run: echo "web: node server.js" > Procfile

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "node_modules/*" ".git/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C91EB87F84049AC94456D90E7A6A2E3  }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_973B127F79D54CC69BF1B89BB3272F30 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6BFA1C0BC2AB41ADBC26662A653053D0 }}

      - name: Set Azure Web App Config
        run: |
          az webapp config appsettings set --name sprache --resource-group <YourResourceGroup> --settings WEBSITES_PORT=8080

      - name: Deploy to Azure Web App via ZIP Deploy
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sprache'
          slot-name: 'Production'
          package: release.zip

      - name: Show deployment logs
        run: az webapp log tail --name sprache --resource-group <YourResourceGroup>
